name = "poopshow"
description = "the theme formerly know as s***show"
license = "MIT"
licenselink = "http://opensource.org/licenses/MIT"
homepage = "http://github.com/esell/poopshow"
source_repo = "http://github.com/esell/poopshow"
tags = ["blog"]
features = ["blog", ]

[author]
    name = "esell"
    homepage = "http://esell.github.io"
